name: Maintain Webring

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0/15 * * * *
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
            ref: main
            token: ${{ secrets.GITHUB_TOKEN }}

      - uses: pnpm/action-setup@v2
        with:
            version: 8

      - uses: actions/setup-node@v3
        with:
            node-version: 18
            cache: "pnpm"

      - name: Run webring maintainance
        run: |
            pnpm install
            pnpm maintain

      - name: Commit & Merge
        run: |
          # Define variables for repository name and branch
          repository="cskartikey/webring"
          branch="auto-maintain-branch"
          echo(name: Maintain Webring

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0/15 * * * *
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
            ref: main
            token: ${{ secrets.GITHUB_TOKEN }}

      - uses: pnpm/action-setup@v2
        with:
            version: 8

      - uses: actions/setup-node@v3
        with:
            node-version: 18
            cache: "pnpm"

      - name: Run webring maintainance
        run: |
            pnpm install
            pnpm maintain

      - name: Commit & Merge
        run: |
          # Define variables for repository name and branch
          repository="cskartikey/webring"
          branch="auto-maintain-branch"
      
          # Check if the branch exists
          if git show-ref --verify --quiet "refs/heads/$branch"; then
            echo "Deleting the branch"
            git push origin --delete --force $branch
            git checkout -b $branch
          else
            echo "Creating the branch"
            git checkout -b $branch
          fi
      
          # Check if there are changes to commit after checking out the branch
          if ! git diff-index --quiet HEAD --; then
            echo "lets debug :sob:"
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
      
            git add .
            git commit -m "Maintain Webring"
            git push origin $branch
            echo "Changes were committed."
      
            gh pr create --title "Maintain Webring" --body "Maintain Webring" --base main --head $branch
            gh pr merge $branch --squash --auto --delete-branch --subject "Maintain Webring" --body "Maintain Webring"
          else
            echo "No changes to commit."
          fi

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
